<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>TypeFlow.App</RootNamespace>
    <AssemblyName>TypeFlow</AssemblyName>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <NoWarn>$(NoWarn);WFAC010</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TypeFlow.Core\TypeFlow.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="assets\typeflow_shortcuts.csv" LogicalName="TypeFlow.defaults.csv" />
  </ItemGroup>

</Project>